name: Code build and Deploy 
on: push 
jobs:
 CICDjob:
  runs-on: ubuntu-latest
  steps:
  - name: Clone the current repository on the runner
    uses: actions/checkout@v4
  - name: Setup Java 17 and maven 
    uses: actions/setup-java@v4
    with:
     distribution: 'temurin'
     java-version: '17'
     cache: 'maven'
  - name: Build with Maven 
    run:  mvn package
  - name: Install docker 
    uses: docker/setup-docker-action@v4
  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  - name: Build and push
    uses: docker/build-push-action@v6
    with:
     context: .
     push: true 
     tags: ${{ secrets.DOCKERHUB_USERNAME }}/myprojectimage:${{ github.run_number }}
  - name: Update values.yaml file to trigger deployment via argocd to Kubernetes
    run: |
      cd argocddeploy
      echo ${{ github.run_number }}
      git config --global user.name 'GitHub Actions'
      git config --global user.email 'actions@github.com'
      sed -i "s/^  tag: .*/  tag: ${{ github.run_number }}/" values.yaml
      git add .
      git commit -m "Update file values.yaml"
      git push
